# Generated by Django 4.1.5 on 2023-01-04 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=50, null=True)),
                ('student_id', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_checkin', models.TimeField()),
                ('time_checkout', models.TimeField()),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='student_attendance_system.students')),
            ],
        ),
    ]
