# Generated by Django 4.1.5 on 2023-01-04 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
