# Generated by Django 4.1.5 on 2023-01-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance_system_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='present_or_absent',
            field=models.BooleanField(default=False),
        ),
    ]
