# Generated by Django 4.1.5 on 2023-01-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance_system_backend', '0002_attendance_present_or_absent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='time_checkin',
            field=models.TimeField(default='20:31'),
        ),
    ]
